---
title: "Danaher_plot output"
output: 
html_document:
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("danaher.R")
library(knitr)
```

This is an result for the gene singatures as well as assigned cell type for each cluster based on Danaher et al. 

```{r ,results='asis'}
knitr::opts_chunk$set(cache=TRUE)

for( i in 1:length(mean_score[1,])){
print(visualize_me(mean_score[,i],cell_list[i],analysis_results$tsne[c("TSNE.1","TSNE.2")],title=names(cell_list)[i]))

#print(plot(mean_score[,i],type = "h",xlab="Single Cell",ylab=colnames(mean_score)[i]))
h <-hist(mean_score[,i],plot = FALSE)

h<- plot(h, freq = TRUE, labels =TRUE, ylim=c(0, 1.2*max(h$counts)),main=c(names(cell_list)[i]," Score per Single Cell"),xlab=paste(sep=" ",names(cell_list)[i],"Expression Level"),ylab="Numbers of cells")
#lay_out(list(h, 1, 1),
#       list(vm, 1, 2))
}
 
sig_plot <- visualize_clusters(cluster_tsne$cell_type,cluster_tsne[c("TSNE.1","TSNE.2")],title="Danaher cell-type labels",legend_anno= sort(unique(cluster_tsne[,"name_type"])))+scale_color_manual(values = colorRampPalette(c("blue", "red","yellow"))( length(sort(unique(cluster_tsne[,"name_type"])))))+  annotate("text", x = tsne_center[, 1], y = tsne_center[, 2], size = 5,label=c(1:length(tsne_center[,1])))

sig_plot

counter <-1
colnames(score_by_cluster) <- names(cell_list)
apply(score_by_cluster, 1,function(x) {plot(x,ylab="mean expression level per cell",xlab="cell type", main=c("Cluster",counter))
text(x, names(cell_list), cex=0.6, pos=4, col="red")
sum_table <- kable(all_type_expr_table[all_type_expr_table$Cluster == counter,])
print(sum_table)
cat("\n")
counter <<- counter + 1})

```


